require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000
  Exclude:
    - db/schema.rb
    - bin/

#################### Style ###########################

Style/CommentAnnotation:
  Keywords:
    - TODO-SNAPCON
    - TODO
    - OPTIMIZE
    - HACK
    - REVIEW

##################### Metrics ##################################

##################### Rails ##################################

Rails:
  Enabled: true

##################### RSpec ##################################

FactoryBot/AttributeDefinedStatically:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/ability/*"

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Style

Metrics/BlockLength:
  Exclude:
    - 'spec/factories/*'

Metrics/LineLength:
  Enabled: True
  Max: 100
  Exclude:
    - 'spec/factories/*'


Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  Enabled: false

# TODO: Enable after upgrading rubocop
# Style/StringConcatenation:
#   Enabled: True
